#!/usr/bin/env python3
import sys
src, dst = sys.argv[1], sys.argv[2]
data = open(src, 'rb').read()
with open(dst, 'w') as f:
    f.write("/* generated by tools/embed.py from %s · do not edit */\n" % src)
    f.write("unsigned char APP_HTML[] = {\n")
    for i in range(0, len(data), 20):
        f.write("  " + ",".join(str(b) for b in data[i:i+20]) + ",\n")
    f.write("};\nunsigned int APP_HTML_LEN = %du;\n" % len(data))
print("embedded %d bytes -> %s" % (len(data), dst))
